'use client'

import { useState } from 'react'
import { ArrowUpRight, ChevronDown, Download, Mail, Menu, X } from 'lucide-react'

const headshot = 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/IMG_3169-gPTd6MPbhwXLKDIJoXrRWeQnZIvPnB.jpg'
const links = { github: 'https://github.com/atharv51', linkedin: 'https://www.linkedin.com/in/atharv-singh-3902bb261', resume: '/Atharv Singh Solanki - Resume.pdf' }

const skillGroups = [
  { title: 'Languages', items: [['C++', 'cplusplus'], ['JavaScript', 'javascript']] },
  { title: 'Frontend', items: [['React.js', 'react'], ['HTML5 · CSS3', 'html5'], ['Tailwind CSS', 'tailwindcss']] },
  { title: 'Backend & APIs', items: [['Node.js', 'nodejs'], ['Express.js', 'express'], ['REST APIs', 'api']] },
  { title: 'Databases', items: [['SQL', 'mysql']] },
  { title: 'Cloud & Deployment', items: [['AWS EC2 · AWS S3', 'aws'], ['Vercel', 'vercel'], ['Gearset', 'gearset']] },
  { title: 'Tools', items: [['Git · GitHub · Bitbucket', 'git'], ['Jira', 'jira'], ['Figma', 'figma'], ['Vercel v0 · Claude · Antigravity', 'anthropic']] },
  { title: 'CRM', items: [['Salesforce · Sales Cloud', 'salesforce']] },
]
const brandIcon = (slug) => `https://cdn.jsdelivr.net/gh/glincker/thesvg@main/public/icons/${slug}/default.svg`
const projects = [{ title: 'Resumind', eyebrow: 'AI career companion', description: 'An intelligent resume analysis platform that turns a static CV into actionable career direction.', bullets: ['AI-powered resume feedback and scoring', 'Clear, responsive dashboard experience', 'Built for practical, confident job searching'], stack: ['Next.js', 'TypeScript', 'AI SDK'], href: '#' }]

function SectionHeading({ eyebrow, title, intro }) {
  return <div className="section-heading"><p className="eyebrow">{eyebrow}</p><h2>{title}</h2>{intro && <p>{intro}</p>}</div>
}

export default function Page() {
  const [menuOpen, setMenuOpen] = useState(false)
  const [status, setStatus] = useState('idle')
  async function submit(event) {
    event.preventDefault(); setStatus('loading')
    const form = event.currentTarget; const data = Object.fromEntries(new FormData(form))
    try { const response = await fetch('/api/contact', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(data) }); if (!response.ok) throw new Error('Unable to send'); form.reset(); setStatus('success') } catch { setStatus('error') }
  }
  return <main>
    <div className="scroll-progress" />
    <nav className="nav"><a className="brand" href="#top" aria-label="Atharv Singh Solanki home">A<span>.</span></a><div className={`nav-links ${menuOpen ? 'open' : ''}`}><a href="#about" onClick={() => setMenuOpen(false)}>About</a><a href="#experience" onClick={() => setMenuOpen(false)}>Experience</a><a href="#projects" onClick={() => setMenuOpen(false)}>Projects</a><a href="#contact" onClick={() => setMenuOpen(false)}>Contact</a></div><a className="nav-cta" href={links.resume}>Resume <Download size={15} /></a><button className="menu-button" onClick={() => setMenuOpen(!menuOpen)} aria-label={menuOpen ? 'Close menu' : 'Open menu'}>{menuOpen ? <X /> : <Menu />}</button></nav>

    <section className="hero section-wrap" id="top"><div className="hero-copy reveal"><p className="eyebrow">Software Engineer / Builder</p><h1>Building thoughtful<br /><em>digital experiences.</em></h1><p className="hero-text">I am Atharv Singh Solanki, a software engineer focused on designing reliable systems and delivering clear, high-quality digital products.</p><div className="hero-actions"><a className="button button-primary" href="#projects">See my work <ArrowUpRight size={17} /></a><a className="text-link" href="#contact">Let&apos;s connect <span>↗</span></a></div></div><div className="hero-visual reveal"><div className="portrait-frame"><img src={headshot} alt="Atharv Singh Solanki in a navy blazer" /></div><div className="availability"><span /> Available for opportunities</div></div><a className="scroll-cue" href="#about">Scroll to explore <ChevronDown size={16} /></a></section>

    <section className="section-wrap about" id="about"><SectionHeading eyebrow="01 / About me" title="Turning ideas into reliable solutions." /><div className="about-grid"><div className="about-copy"><p className="large-copy">I am a Computer Science and Engineering graduate with hands-on experience in software development, full-stack applications, AI-powered solutions, and enterprise software delivery.</p><p>I enjoy turning complex problems into reliable, practical solutions through structured thinking, clean implementation, and continuous learning. My experience spans application development, REST APIs, database integration, version control, deployments, and production support.</p><p>I am particularly interested in building products that combine thoughtful engineering with real-world impact.</p><div className="socials"><a href={links.github} aria-label="GitHub"><img src={brandIcon('github')} alt="" /></a><a href={links.linkedin} aria-label="LinkedIn"><img src={brandIcon('linkedin')} alt="" /></a><a href="mailto:atharvsingh22122004@gmail.com" aria-label="Email"><Mail size={18} /></a></div></div><div className="facts"><div><span>Based in</span><strong>India · Open to opportunities</strong></div><div><span>Focus</span><strong>Software Engineering · Full-Stack Development · AI Solutions</strong></div><div><span>Currently</span><strong>Building · Learning · Solving · Shipping</strong></div></div></div></section>

    <section className="section-wrap" id="experience"><SectionHeading eyebrow="02 / Experience" title="Professional experience." /><div className="timeline"><article className="timeline-item"><div className="timeline-date">Jan 2026 — Present</div><div><h3>Software Development Engineer <span>·</span> American Chase LLP</h3><p>Contributing to enterprise application development, defect resolution, releases, deployments, and production support while collaborating with development and QA teams.</p><div className="tags"><span>Git</span><span>Bitbucket</span><span>Jira</span><span>Gearset</span><span>Salesforce</span></div></div></article><article className="timeline-item"><div className="timeline-date">Jun 2025 — Jul 2025</div><div><h3>Web Development Intern <span>·</span> Django Softwares Pvt. Ltd.</h3><p>Developed full-stack and AI-powered applications, built REST APIs and database integrations, and contributed to a vacation rental platform.</p><div className="tags"><span>React.js</span><span>Next.js</span><span>Node.js</span><span>MongoDB</span><span>React Native</span></div></div></article></div></section>

    <section className="section-wrap skills-section" id="skills"><SectionHeading eyebrow="03 / Toolkit" title="Technologies I work with." /><div className="skills-grid">{skillGroups.map(group => <div className="skill-group" key={group.title}><h3>{group.title}</h3><div>{group.items.map(([item, slug]) => <span className="skill-pill" key={item}><img src={brandIcon(slug)} alt="" /><strong>{item}</strong></span>)}</div></div>)}</div></section>

    <section className="section-wrap" id="projects"><SectionHeading eyebrow="04 / Selected work" title="Resumind." /><div className="project-card"><div className="project-index">01</div><div className="project-content"><p className="eyebrow">AI Resume Analyzer</p><h3>Resume analysis with actionable direction.</h3><p>Resumind helps users evaluate resume quality against specific job descriptions and improve their applications through targeted, AI-assisted feedback.</p><ul><li>Analyzes resumes against specific job descriptions.</li><li>Generates ATS compatibility scores and keyword analysis.</li><li>Provides targeted suggestions for improving resume content.</li><li>Uses Claude Sonnet-4 for resume analysis.</li><li>Provides a responsive interface centered on a clear analysis workflow.</li></ul><p className="project-engineering"><strong>Engineering:</strong> Serverless architecture with Puter.js for authentication, file storage, AI processing, and database management. Built with React.js, TypeScript, Tailwind CSS v4, React Router v7, and Zustand.</p><div className="project-footer"><div className="tags"><span>React.js</span><span>TypeScript</span><span>Tailwind CSS</span><span>React Router</span><span>Zustand</span><span>Puter.js</span><span>Claude Sonnet-4</span><span>AI</span></div><a className="text-link" href="#">View project <ArrowUpRight size={16} /></a></div></div><div className="project-art"><div className="mini-window"><div className="window-top"><span /><span /><span /></div><div className="chart-line"><i /><i /><i /><i /><i /></div><div className="mini-row"><b /><b /><b /></div></div></div></div></section>

    <section className="section-wrap split-section"><div><SectionHeading eyebrow="05 / Education" title="Education." /><div className="education"><p>Computer Science and Engineering</p><strong>Bachelor of Technology</strong><span>2022 — 2026 · Medi-Caps University</span><p>Built a foundation in computer science, programming, software development, problem solving, and modern application technologies.</p><p>Higher Secondary Education · Himalaya International School</p><span>2021 — 2022</span></div></div><div><SectionHeading eyebrow="06 / Beyond code" title="Learning beyond the editor." /><p className="large-copy">Engineering is more than writing code. I continuously strengthen my problem-solving ability, explore new technologies, and challenge myself through practical projects and competitions.</p><div className="journey-list"><div>01 <span>Full-Stack Development — HCL Tech&apos;s 240-hour Full Stack Developer with AI program</span></div><div>02 <span>Generative AI — NPTEL Programming with Gen AI certification</span></div><div>03 <span>Hackathon — 4th place at Hackmivo Hackathon</span></div><div>04 <span>Problem Solving — 2 LeetCode badges</span></div></div></div></section>

    <section className="contact section-wrap" id="contact"><div><SectionHeading eyebrow="07 / Let&apos;s build" title="Have a problem worth solving?" intro="I am interested in opportunities to learn, build meaningful products, collaborate with strong teams, and take on challenging technical problems." /><p className="contact-person">Atharv Singh Solanki<br />India · Open to opportunities</p><a className="email-link" href="mailto:atharvsingh22122004@gmail.com">atharvsingh22122004@gmail.com <ArrowUpRight size={18} /></a></div><form onSubmit={submit} className="contact-form"><input name="website" tabIndex={-1} autoComplete="off" className="honeypot" /><label>Name<input name="name" required placeholder="Your name" /></label><label>Email<input name="email" type="email" required placeholder="you@example.com" /></label><label>Message<textarea name="message" required minLength={10} placeholder="Tell me a little about what you&apos;re working on..." rows={5} /></label><button className="button button-primary" disabled={status === 'loading'}>{status === 'loading' ? 'Sending…' : 'Send message'} <ArrowUpRight size={17} /></button>{status === 'success' && <p className="form-status success">Thanks — your message is on its way.</p>}{status === 'error' && <p className="form-status error">Something went wrong. Please try again or email me directly.</p>}</form></section>
    <footer className="footer section-wrap"><span>© 2025 Atharv Singh Solanki</span><span>Designed & built with intention.</span><a href="#top">Back to top ↑</a></footer>
  </main>
}
